export const GET_DETAILS = "GET_DETAILS";
export const POST_DETAILS = "POST_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const DELETE_DETAILS = "DELETE_DETAILS";

/*
//suraj
 export const GET_DETAILS = "GET_DETAILS";
export const ACTIONS = {
  GET_DETAILS: "GET_DETAILS",
  GET_DETAILS_SUCCESS: "GET_DETAILS_SUCCESS",
  GET_DETAILS_FAILURE: "GET_DETAILS_FAILURE",
};
*/
